version: "2"
services:
  odoo:
    image: odoo:11.0
    container_name: odoo11
    ports:
        - 8070:8069
    environment:
        - DB_PORT_5432_TCP_ADDR=odoo11_db
        - DB_PORT_5432_TCP_PORT=5432
        - DB_ENV_POSTGRES_USER=odoo
        - DB_ENV_POSTGRES_PASSWORD=odoo
    links:
        - db:db
    volumes:
        - ./extra-addons:/mnt/extra-addons
        - ./filestore:/var/lib/odoo
        - ./odoo.conf:/etc/odoo/odoo.conf

  db:
    image: postgres:9.6
    container_name: odoo11_db
    environment:
        POSTGRES_USER: odoo
        POSTGRES_PASSWORD: odoo
    volumes:
        - ./data:/var/lib/postgresql/data
